use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn invoke_handler_command_names() -> BTreeSet<String> {
    let lib_src = include_str!("lib.rs");
    let handler_block = lib_src
        .split("tauri::generate_handler![")
        .nth(1)
        .expect("invoke_handler block")
        .split("])")
        .next()
        .expect("closing bracket");

    handler_block
        .lines()
        .filter_map(|l| l.trim().strip_suffix(','))
        .map(|l| l.rsplit("::").next().unwrap().trim().to_string())
        .filter(|s| !s.is_empty())
        .collect()
}

fn app_manifest_command_names() -> BTreeSet<String> {
    let build_src = include_str!("../build.rs");
    let app_block = build_src
        .split("APP_COMMANDS: &[&str] = &[")
        .nth(1)
        .expect("APP_COMMANDS block")
        .split("];")
        .next()
        .expect("closing bracket");

    app_block
        .lines()
        .filter_map(|l| {
            let l = l.trim().trim_end_matches(',');
            l.strip_prefix('"')
                .and_then(|s| s.strip_suffix('"'))
                .map(String::from)
        })
        .collect()
}

fn command_permissions_from_default_toml(src: &str) -> BTreeSet<String> {
    src.lines()
        .map(str::trim)
        .filter_map(|line| {
            let value = line.trim_end_matches(',').trim_matches('"');
            value
                .strip_prefix("allow-")
                .map(|command| command.replace('-', "_"))
        })
        .collect()
}

fn command_permissions_from_commands_allow(src: &str) -> BTreeSet<String> {
    let mut commands = BTreeSet::new();
    let mut in_allow_block = false;

    for line in src.lines().map(str::trim) {
        if line.starts_with("commands.allow = [") {
            if let Some(inline) = line
                .strip_prefix("commands.allow = [")
                .and_then(|value| value.strip_suffix(']'))
            {
                for command in inline.split(',') {
                    let command = command.trim().trim_matches('"');
                    if !command.is_empty() {
                        commands.insert(command.to_string());
                    }
                }
                continue;
            }
            in_allow_block = true;
            continue;
        }
        if in_allow_block && line == "]" {
            in_allow_block = false;
            continue;
        }
        if in_allow_block {
            let command = line.trim_end_matches(',').trim_matches('"');
            if !command.is_empty() {
                commands.insert(command.to_string());
            }
        }
    }

    commands
}

fn app_acl_command_permissions() -> BTreeSet<String> {
    let mut commands =
        command_permissions_from_default_toml(include_str!("../permissions/default.toml"));
    for src in [
        include_str!("../permissions/autogenerated/run_data_admin_command.toml"),
        include_str!("../permissions/autogenerated/run_external_connector_command.toml"),
        include_str!("../permissions/autogenerated/run_filesystem_access_command.toml"),
        include_str!("../permissions/autogenerated/run_filesystem_export_command.toml"),
        include_str!("../permissions/autogenerated/run_project_execution_command.toml"),
    ] {
        commands.extend(command_permissions_from_commands_allow(src));
    }
    commands
}

// Collect every direct command dispatched by a privileged broker.
fn broker_only_command_names() -> BTreeSet<String> {
    let mut commands = BTreeSet::new();
    for src in [
        include_str!("../permissions/data_admin.toml"),
        include_str!("../permissions/external_connectors.toml"),
        include_str!("../permissions/filesystem_access.toml"),
        include_str!("../permissions/filesystem_export.toml"),
        include_str!("../permissions/project_execution.toml"),
    ] {
        commands.extend(command_permissions_from_commands_allow(src));
    }
    commands.extend(
        crate::commands::privileged_command_broker::SCOPES
            .iter()
            .flat_map(|scope| scope.allowlist)
            .map(|command| command.to_string()),
    );
    commands
}

fn broker_only_commands_in(surface: &BTreeSet<String>) -> Vec<String> {
    broker_only_command_names()
        .into_iter()
        .filter(|command| surface.contains(command))
        .collect()
}

fn command_security_manifest() -> serde_json::Value {
    serde_json::from_str(include_str!("../permissions/command-security.json"))
        .expect("valid command-security.json")
}

fn manifest_string_array(manifest: &serde_json::Value, key: &str) -> BTreeSet<String> {
    manifest
        .get(key)
        .and_then(|value| value.as_array())
        .unwrap_or_else(|| panic!("{} array missing from command-security.json", key))
        .iter()
        .map(|value| {
            value
                .as_str()
                .unwrap_or_else(|| panic!("{} must contain strings", key))
                .to_string()
        })
        .collect()
}

struct NativeConfirmationStep {
    function: String,
    requires: String,
}

struct NativeConfirmationContract {
    command: String,
    source: String,
    steps: Vec<NativeConfirmationStep>,
}

fn native_confirmed_manifest_entries() -> Vec<NativeConfirmationContract> {
    command_security_manifest()
        .get("nativeConfirmedCommands")
        .and_then(|value| value.as_array())
        .expect("nativeConfirmedCommands array")
        .iter()
        .map(|entry| {
            let command = entry
                .get("command")
                .and_then(|value| value.as_str())
                .expect("nativeConfirmedCommands command")
                .to_string();
            let source = entry
                .get("source")
                .and_then(|value| value.as_str())
                .expect("nativeConfirmedCommands source")
                .to_string();
            let steps = match entry.get("confirmationPath") {
                Some(value) => value
                    .as_array()
                    .filter(|path| !path.is_empty())
                    .expect("nativeConfirmedCommands confirmationPath must be a non-empty array")
                    .iter()
                    .map(|step| NativeConfirmationStep {
                        function: step
                            .get("function")
                            .and_then(|value| value.as_str())
                            .expect("nativeConfirmedCommands confirmationPath function")
                            .to_string(),
                        requires: step
                            .get("requires")
                            .and_then(|value| value.as_str())
                            .expect("nativeConfirmedCommands confirmationPath requires")
                            .to_string(),
                    })
                    .collect(),
                None => {
                    let function = entry
                        .get("confirmationFunction")
                        .and_then(|value| value.as_str())
                        .map(str::to_string)
                        .unwrap_or_else(|| command.clone());
                    let requires = entry
                        .get("requires")
                        .and_then(|value| value.as_str())
                        .expect("nativeConfirmedCommands requires")
                        .to_string();
                    vec![NativeConfirmationStep { function, requires }]
                }
            };
            NativeConfirmationContract {
                command,
                source,
                steps,
            }
        })
        .collect()
}

fn rust_source_files(dir: &Path, files: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            rust_source_files(&path, files);
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            files.push(path);
        }
    }
}

/// True for a `cfg` predicate that holds only under `cargo test`: the bare
/// `test`, or an `all(...)` whose top-level list carries a bare `test`.
/// `any(test, ...)` and `not(test)` are deliberately excluded because both
/// can hold in a production build, so a module carrying them is production
/// code the source-scanning guardrails must keep seeing.
fn cfg_is_test_only(predicate: &str) -> bool {
    let trimmed = predicate.trim();
    if trimmed == "test" {
        return true;
    }
    let Some(list) = trimmed
        .strip_prefix("all(")
        .and_then(|rest| rest.strip_suffix(')'))
    else {
        return false;
    };
    let mut depth = 0usize;
    list.split(|ch| {
        match ch {
            '(' => depth += 1,
            ')' => depth = depth.saturating_sub(1),
            _ => {}
        }
        ch == ',' && depth == 0
    })
    .any(|item| item.trim() == "test")
}

/// Byte offset just past the `}` closing a block whose opening `{` the caller
/// already consumed, or `None` when the block never closes. Braces inside
/// string, raw-string, and character literals and inside `//` and `/* */`
/// comments do not count, so a `{` in a test fixture cannot swallow the file.
fn end_of_block(source: &str, body_start: usize) -> Option<usize> {
    let bytes = source.as_bytes();
    let mut index = body_start;
    let mut depth = 1usize;
    while index < bytes.len() {
        match bytes[index] {
            b'{' => {
                depth += 1;
                index += 1;
            }
            b'}' => {
                depth -= 1;
                index += 1;
                if depth == 0 {
                    return Some(index);
                }
            }
            b'/' if bytes.get(index + 1) == Some(&b'/') => {
                index = match source[index..].find('\n') {
                    Some(offset) => index + offset + 1,
                    None => bytes.len(),
                };
            }
            b'/' if bytes.get(index + 1) == Some(&b'*') => {
                index = end_of_block_comment(source, index + 2);
            }
            b'"' => index = end_of_string_literal(source, index + 1),
            b'r' | b'b' => match raw_string_hashes(source, index) {
                Some((quote, hashes)) => index = end_of_raw_string(source, quote + 1, hashes),
                None => index += 1,
            },
            b'\'' => index = end_of_char_literal(source, index),
            _ => index += 1,
        }
    }
    None
}

/// Offset just past the terminating `*/`, honouring Rust's nested block
/// comments. `index` points just past the opening `/*`.
fn end_of_block_comment(source: &str, mut index: usize) -> usize {
    let bytes = source.as_bytes();
    let mut depth = 1usize;
    while index < bytes.len() {
        if bytes[index] == b'/' && bytes.get(index + 1) == Some(&b'*') {
            depth += 1;
            index += 2;
        } else if bytes[index] == b'*' && bytes.get(index + 1) == Some(&b'/') {
            depth -= 1;
            index += 2;
            if depth == 0 {
                return index;
            }
        } else {
            index += 1;
        }
    }
    bytes.len()
}

/// Offset just past the closing `"`. `index` points just past the opening
/// quote; `\"` and `\\` do not terminate the literal.
fn end_of_string_literal(source: &str, mut index: usize) -> usize {
    let bytes = source.as_bytes();
    while index < bytes.len() {
        match bytes[index] {
            b'\\' => index += 2,
            b'"' => return index + 1,
            _ => index += 1,
        }
    }
    bytes.len()
}

/// `(offset of the opening quote, hash count)` when `index` starts a raw
/// string (`r"`, `r#"`, `br"`, `br##"`, ...) rather than an identifier that
/// merely begins with `r` or `b`.
fn raw_string_hashes(source: &str, index: usize) -> Option<(usize, usize)> {
    let bytes = source.as_bytes();
    let previous = index.checked_sub(1).map(|before| bytes[before]);
    if previous.is_some_and(|byte| byte.is_ascii_alphanumeric() || byte == b'_') {
        return None;
    }
    let mut cursor = index;
    if bytes[cursor] == b'b' {
        cursor += 1;
    }
    if bytes.get(cursor) != Some(&b'r') {
        return None;
    }
    cursor += 1;
    let hashes_start = cursor;
    while bytes.get(cursor) == Some(&b'#') {
        cursor += 1;
    }
    if bytes.get(cursor) != Some(&b'"') {
        return None;
    }
    Some((cursor, cursor - hashes_start))
}

/// Offset just past a raw string's terminating `"` plus its `#` run.
/// `index` points just past the opening quote.
fn end_of_raw_string(source: &str, mut index: usize, hashes: usize) -> usize {
    let bytes = source.as_bytes();
    let closing = format!("\"{}", "#".repeat(hashes));
    match source[index..].find(&closing) {
        Some(offset) => {
            index += offset + closing.len();
            index
        }
        None => bytes.len(),
    }
}

/// Offset just past a character literal's closing `'`, or just past the
/// opening `'` when this is a lifetime rather than a literal.
fn end_of_char_literal(source: &str, index: usize) -> usize {
    let bytes = source.as_bytes();
    if bytes.get(index + 1) == Some(&b'\\') {
        let mut cursor = index + 2;
        if bytes.get(cursor) == Some(&b'u') {
            while cursor < bytes.len() && bytes[cursor] != b'}' {
                cursor += 1;
            }
            cursor += 1;
        } else {
            cursor += 1;
        }
        if bytes.get(cursor) == Some(&b'\'') {
            return cursor + 1;
        }
        return index + 1;
    }
    if let Some(character) = source[index + 1..].chars().next() {
        let after = index + 1 + character.len_utf8();
        if bytes.get(after) == Some(&b'\'') {
            return after + 1;
        }
    }
    index + 1
}

/// Source with every inline test module excised. A `#[cfg(test)]` attribute
/// (or a compound test-only form such as `#[cfg(all(test, feature =
/// "desktop"))]`) followed, after optional whitespace and other attribute
/// lines, by `mod <ident> {` opens an inline test module; its body is matched
/// brace for brace, replaced by the newlines it spanned, and the scan
/// continues after its closing brace. Production code on *both* sides of a
/// test module therefore stays visible to the source-scanning guardrails, and
/// every surviving line keeps its original line number so a guardrail can
/// report `file:line` accurately. A `#[cfg(test)] mod tests;` declaration, or
/// a `#[cfg(test)]` on a `use`, field, or function, does not match.
fn production_half(source: &str) -> String {
    let inline_test_module = regex::Regex::new(
        r"#\[cfg\(([^\]]*)\)\](?:\s*#\[[^\]]*\])*\s*mod\s+[A-Za-z_][A-Za-z0-9_]*\s*\{",
    )
    .expect("inline test module pattern");

    let mut kept = String::with_capacity(source.len());
    let mut cursor = 0usize;
    loop {
        let Some(captures) = inline_test_module.captures(&source[cursor..]) else {
            kept.push_str(&source[cursor..]);
            return kept;
        };
        let matched = captures.get(0).expect("whole match");
        let start = cursor + matched.start();
        let body = cursor + matched.end();
        let predicate = captures.get(1).map_or("", |group| group.as_str());
        if !cfg_is_test_only(predicate) {
            kept.push_str(&source[cursor..body]);
            cursor = body;
            continue;
        }
        kept.push_str(&source[cursor..start]);
        // An unbalanced module body cannot be excised safely; drop the rest
        // rather than let test code count as production.
        let Some(end) = end_of_block(source, body) else {
            return kept;
        };
        for _ in 0..source[start..end].matches('\n').count() {
            kept.push('\n');
        }
        cursor = end;
    }
}

fn tracing_instrument_attributes(source: &str) -> Vec<(usize, &str)> {
    let marker = concat!("#[", "tracing::instrument");
    let mut attributes = Vec::new();
    let mut index = 0;

    while let Some(relative_start) = source[index..].find(marker) {
        let start = index + relative_start;
        let Some(relative_end) = source[start..].find(']') else {
            break;
        };
        let end = start + relative_end + 1;
        let line = source[..start].lines().count() + 1;
        attributes.push((line, &source[start..end]));
        index = end;
    }

    attributes
}

fn tracing_field_assignment_is_unsafe(attribute: &str) -> bool {
    let normalized: String = attribute
        .to_ascii_lowercase()
        .chars()
        .filter(|ch| !ch.is_whitespace())
        .collect();
    if !normalized.contains("fields(") {
        return false;
    }

    let unsafe_fields = [
        "raw",
        "password",
        "passwd",
        "secret",
        "token",
        "api_key",
        "apikey",
        "credential",
        "authorization",
        "database_url",
        "db_url",
        "path",
        "src_path",
        "dest_path",
        "source_path",
        "project_path",
        "project_root",
        "env_file_path",
        "working_dir",
    ];

    unsafe_fields.iter().any(|field| {
        normalized.contains(&format!("fields({}=", field))
            || normalized.contains(&format!(",{}=", field))
    })
}

// Extract functions carrying bare or conditional Tauri command attributes.
fn tauri_command_annotated_fn_names(source: &str) -> Vec<String> {
    let attribute_marker = concat!("tauri", "::command");
    let lines: Vec<&str> = source.lines().collect();
    let mut names = Vec::new();
    for (index, line) in lines.iter().enumerate() {
        let trimmed = line.trim_start();
        if !trimmed.starts_with("#[") || !trimmed.contains(attribute_marker) {
            continue;
        }
        // Allow a few intervening attributes (e.g. tracing::instrument)
        // between the annotation and the fn signature.
        for following in lines.iter().skip(index + 1).take(8) {
            if let Some(name) = fn_name_in_signature_line(following) {
                names.push(name);
                break;
            }
        }
    }
    names
}

fn fn_name_in_signature_line(line: &str) -> Option<String> {
    let mut tokens = line.split_whitespace();
    tokens.find(|token| *token == "fn")?;
    let name: String = tokens
        .next()?
        .chars()
        .take_while(|ch| ch.is_ascii_alphanumeric() || *ch == '_')
        .collect();
    (!name.is_empty()).then_some(name)
}

fn function_body_contains(source: &str, fn_name: &str, needle: &str) -> bool {
    let marker = format!("fn {}", fn_name);
    let mut search_start = 0;

    while let Some(relative_start) = source[search_start..].find(&marker) {
        let signature_start = search_start + relative_start;
        let tail_start = signature_start + marker.len();
        if source[tail_start..]
            .chars()
            .next()
            .is_some_and(|ch| ch == '_' || ch.is_ascii_alphanumeric())
        {
            search_start = tail_start;
            continue;
        }
        let Some(boundary_offset) = source[tail_start..].find([';', '{']) else {
            return false;
        };
        let boundary = tail_start + boundary_offset;
        if source.as_bytes()[boundary] == b';' {
            search_start = boundary + 1;
            continue;
        }

        let mut depth = 0usize;
        let mut body_closed = false;
        for (offset, ch) in source[boundary..].char_indices() {
            if ch == '{' {
                depth += 1;
            } else if ch == '}' {
                depth = depth.saturating_sub(1);
                if depth == 0 {
                    if source[boundary..boundary + offset].contains(needle) {
                        return true;
                    }
                    search_start = boundary + offset + 1;
                    body_closed = true;
                    break;
                }
            }
        }
        if !body_closed {
            return false;
        }
    }

    false
}

#[test]
fn function_body_match_skips_declarations_and_name_prefixes() {
    let source = r#"
        trait Ports { async fn confirm_replacement(&self); }
        fn confirm_replacement_preview() { confirm_sensitive_action(); }
        impl Ports for DesktopPorts {
            async fn confirm_replacement(&self) { confirm_sensitive_action(); }
        }
    "#;

    assert!(function_body_contains(
        source,
        "confirm_replacement",
        "confirm_sensitive_action("
    ));
    assert!(!function_body_contains(
        "async fn confirm_replacement() {",
        "confirm_replacement",
        "confirm_sensitive_action("
    ));
}

// Guard: the `APP_COMMANDS` list in `build.rs` must contain every
// `#[tauri::command]` handler registered in `invoke_handler!`. If they
// drift, the ACL manifest won't gate the new command - any webview can
// call it.
#[test]
fn app_commands_list_matches_invoke_handler() {
    let lib_cmds = invoke_handler_command_names();
    let build_cmds = app_manifest_command_names();

    let missing_in_build: Vec<_> = lib_cmds.difference(&build_cmds).collect();
    let missing_in_lib: Vec<_> = build_cmds.difference(&lib_cmds).collect();
    assert!(
        missing_in_build.is_empty() && missing_in_lib.is_empty(),
        "APP_COMMANDS and invoke_handler! drifted.\n  in lib.rs but not build.rs: {:?}\n  in build.rs but not lib.rs: {:?}",
        missing_in_build,
        missing_in_lib,
    );
}

#[test]
fn csp_blocks_unsafe_inline_in_style_src() {
    let conf: serde_json::Value = serde_json::from_str(include_str!("../tauri.conf.json"))
        .expect("tauri.conf.json must parse");
    let csp = conf
        .pointer("/app/security/csp")
        .and_then(|v| v.as_str())
        .expect("CSP must be defined in tauri.conf.json");

    let style_src = csp
        .split(';')
        .map(str::trim)
        .find(|d| d.starts_with("style-src ") || *d == "style-src")
        .expect("CSP must declare a style-src directive");
    assert!(
        !style_src.contains("'unsafe-inline'"),
        "style-src must not contain 'unsafe-inline': got {style_src:?}"
    );

    // Defense in depth: also forbid 'unsafe-eval' anywhere.
    assert!(
        !csp.contains("'unsafe-eval'"),
        "CSP must not contain 'unsafe-eval' anywhere"
    );
}

/// The main window renders scanned-site and repository text as Markdown. A
/// remote `img-src` allowance would let `![x](https://attacker/p.png)` in a
/// page title beacon out the moment an issue is expanded, which contradicts
/// the enumerated-egress promise on the trust page.
#[test]
fn csp_img_src_never_allows_remote_origins() {
    for (name, source) in [
        ("tauri.conf.json", include_str!("../tauri.conf.json")),
        (
            "tauri.dev.conf.json",
            include_str!("../tauri.dev.conf.json"),
        ),
    ] {
        let conf: serde_json::Value = serde_json::from_str(source).expect("config must parse");
        let csp = conf
            .pointer("/app/security/csp")
            .and_then(|v| v.as_str())
            .expect("CSP must be defined");
        let img_src = csp
            .split(';')
            .map(str::trim)
            .find(|d| d.starts_with("img-src "))
            .expect("CSP must declare img-src");
        for token in img_src.split_whitespace().skip(1) {
            let remote = token == "*"
                || token == "https:"
                || token == "http:"
                || (token.starts_with("http") && !token.contains("localhost"));
            assert!(
                !remote,
                "{name} img-src must not allow remote origins, got {token:?} in {img_src:?}"
            );
        }
    }
}

#[test]
fn dev_csp_is_defined_and_blocks_unsafe_eval() {
    let conf: serde_json::Value = serde_json::from_str(include_str!("../tauri.dev.conf.json"))
        .expect("tauri.dev.conf.json must parse");
    let csp = conf
        .pointer("/app/security/csp")
        .and_then(|v| v.as_str())
        .expect("CSP must be defined in tauri.dev.conf.json");

    let forbidden_eval_directive = format!("'{}'", "unsafe-eval");
    assert!(
        !csp.contains(&forbidden_eval_directive),
        "dev CSP must not contain {forbidden_eval_directive}"
    );
    let script_src = csp
        .split(';')
        .map(str::trim)
        .find(|d| d.starts_with("script-src "))
        .expect("dev CSP must declare a script-src directive");
    assert!(
        script_src.contains("'self'"),
        "dev CSP script-src must include 'self': got {script_src:?}"
    );
}

#[test]
fn app_acl_permissions_cover_registered_commands() {
    let build_cmds = app_manifest_command_names();
    let acl_cmds = app_acl_command_permissions();

    let missing_from_acl: Vec<_> = build_cmds.difference(&acl_cmds).collect();
    let unknown_in_acl: Vec<_> = acl_cmds.difference(&build_cmds).collect();
    assert!(
        missing_from_acl.is_empty() && unknown_in_acl.is_empty(),
        "Tauri ACL permissions drifted from APP_COMMANDS.\n  in build.rs but not ACL: {:?}\n  in ACL but not build.rs: {:?}",
        missing_from_acl,
        unknown_in_acl,
    );
}

// Keep broker-only privileged commands off the direct Tauri IPC surface.
#[test]
fn broker_only_commands_are_not_registered_ipc_commands() {
    let broker_only = broker_only_command_names();
    assert!(
        broker_only.len() >= 50,
        "broker-only command list parsed suspiciously small: {:?}",
        broker_only,
    );

    let handler_leaks = broker_only_commands_in(&invoke_handler_command_names());
    let manifest_leaks = broker_only_commands_in(&app_manifest_command_names());
    assert!(
        handler_leaks.is_empty() && manifest_leaks.is_empty(),
        "Broker-only privileged commands must stay off the Tauri IPC surface; route them through their run_* broker instead.\n  in lib.rs invoke_handler!: {:?}\n  in build.rs APP_COMMANDS: {:?}",
        handler_leaks,
        manifest_leaks,
    );
}

// Negative control: prove the guard above flags a broker-only command that
// reappears on the IPC surface.
#[test]
fn broker_only_registration_guard_detects_reintroduced_commands() {
    let mut surface = invoke_handler_command_names();
    surface.insert("delete_project".to_string());
    assert_eq!(
        broker_only_commands_in(&surface),
        vec!["delete_project".to_string()],
    );
}

#[test]
fn broker_only_commands_carry_no_tauri_command_attribute() {
    let broker_only = broker_only_command_names();
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files = Vec::new();
    rust_source_files(&src_dir, &mut files);
    assert!(!files.is_empty(), "Rust source scan found no files");

    let mut findings = Vec::new();
    for file in files {
        let source = std::fs::read_to_string(&file).expect("read Rust source file");
        for name in tauri_command_annotated_fn_names(&source) {
            if broker_only.contains(&name) {
                let relative = file
                    .strip_prefix(env!("CARGO_MANIFEST_DIR"))
                    .unwrap_or(&file)
                    .display();
                findings.push(format!("{}: {}", relative, name));
            }
        }
    }

    assert!(
        findings.is_empty(),
        "Broker-only privileged commands are dispatched as plain Rust calls by the run_* brokers and must not carry the Tauri command attribute; remove it: {:?}",
        findings,
    );
}

// Negative control: prove the annotation scan sees a broker-only command
// that regains the attribute, in both the bare and cfg_attr forms.
#[test]
fn broker_only_annotation_guard_detects_reannotated_commands() {
    let bare = format!(
        "#[{}]\npub async fn delete_project() {{}}\n",
        concat!("tauri", "::command"),
    );
    assert_eq!(
        tauri_command_annotated_fn_names(&bare),
        vec!["delete_project".to_string()],
    );

    let cfg_attr = format!(
        "#[cfg_attr(feature = \"desktop\", {})]\n#[tracing::instrument(skip_all)]\npub fn run_code_scan() {{}}\n",
        concat!("tauri", "::command"),
    );
    assert_eq!(
        tauri_command_annotated_fn_names(&cfg_attr),
        vec!["run_code_scan".to_string()],
    );
}

#[test]
fn git_is_spawned_only_by_the_hardened_runner() {
    let spawn = regex::Regex::new(r#"Command::new\(\s*"(?:[^"]*/)?git(?:\.exe)?"\s*\)"#)
        .expect("git spawn pattern");
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files = Vec::new();
    rust_source_files(&src_dir, &mut files);
    assert!(!files.is_empty(), "Rust source scan found no files");

    let mut findings = Vec::new();
    let mut runner_spawns = 0;
    for file in files {
        let relative = file
            .strip_prefix(env!("CARGO_MANIFEST_DIR"))
            .unwrap_or(&file)
            .display()
            .to_string();
        if relative.ends_with("_tests.rs") {
            continue;
        }
        let source = std::fs::read_to_string(&file).expect("read Rust source file");
        let hits = spawn.find_iter(&production_half(&source)).count();
        if relative == "src/core/git.rs" {
            runner_spawns = hits;
        } else if hits > 0 {
            findings.push(format!("{relative} ({hits})"));
        }
    }

    assert_eq!(
        runner_spawns, 1,
        "src/core/git.rs must spawn git exactly once, inside hardened_git_command"
    );
    assert!(
        findings.is_empty(),
        "git must be spawned only through the two runners in core::git, run_git and run_git_command, which share one hardened spawn, so every invocation carries the config and environment hardening apart from the single documented https exception. This scan covers src/ only, excluding files named *_tests.rs; crates/cli and crates/engine are not scanned: {:?}",
        findings,
    );
}

// Negative control: the spawn pattern sees absolute and .exe forms.
#[test]
fn git_spawn_guard_detects_every_spelling() {
    let spawn = regex::Regex::new(r#"Command::new\(\s*"(?:[^"]*/)?git(?:\.exe)?"\s*\)"#)
        .expect("git spawn pattern");
    for source in [
        r#"Command::new("git")"#,
        r#"std::process::Command::new("/usr/bin/git")"#,
        r#"tokio::process::Command::new( "git.exe" )"#,
    ] {
        assert!(spawn.is_match(source), "{source}");
    }
    assert!(!spawn.is_match(r#"Command::new("gitleaks")"#));
}

// Negative control: an external test-module declaration must not truncate
// the production code that follows it.
#[test]
fn production_half_keeps_code_after_an_external_test_module_declaration() {
    let source = concat!(
        "#[cfg(test)]\n",
        "mod tests;\n",
        "\n",
        "fn spawn_git() {\n",
        "    Command::new(\"git\");\n",
        "}\n",
    );
    assert!(
        production_half(source).contains(r#"Command::new("git")"#),
        "an external test module declaration must not truncate production code"
    );
}

#[test]
fn production_half_strips_an_inline_test_module() {
    let source = concat!(
        "fn production() {}\n",
        "\n",
        "#[cfg(test)]\n",
        "mod tests {\n",
        "    fn spawn_git() {\n",
        "        Command::new(\"git\");\n",
        "    }\n",
        "}\n",
    );
    let half = production_half(source);
    assert!(half.contains("fn production"));
    assert!(
        !half.contains(r#"Command::new("git")"#),
        "an inline test module's contents must be stripped"
    );
}

// The regression F1 closes: a truncating `production_half` hid every line
// after the first inline test module from all four source-scanning
// guardrails.
#[test]
fn production_half_keeps_production_code_after_an_inline_test_module() {
    let source = concat!(
        "fn before() {}\n",
        "\n",
        "#[cfg(test)]\n",
        "mod tests {\n",
        "    fn spawn_git() {\n",
        "        Command::new(\"git\");\n",
        "    }\n",
        "}\n",
        "\n",
        "fn after() {\n",
        "    Command::new(\"gitleaks\");\n",
        "}\n",
    );
    let half = production_half(source);
    assert!(half.contains("fn before"));
    assert!(
        half.contains("fn after"),
        "production code after an inline test module must survive: {half:?}"
    );
    assert!(half.contains(r#"Command::new("gitleaks")"#));
    assert!(!half.contains(r#"Command::new("git")"#));
    assert_eq!(
        half.matches('\n').count(),
        source.matches('\n').count(),
        "excision must preserve line numbering so guardrails report file:line"
    );
    assert_eq!(
        half.lines().nth(9),
        Some("fn after() {"),
        "every surviving line must keep its original line number"
    );
}

#[test]
fn production_half_excises_every_inline_test_module() {
    let source = concat!(
        "fn first() {}\n",
        "#[cfg(test)]\n",
        "mod early_tests {\n",
        "    const FIXTURE: &str = \"{ unbalanced\";\n",
        "    fn a() { Command::new(\"git\"); }\n",
        "}\n",
        "fn middle() {}\n",
        "#[cfg(all(test, feature = \"desktop\"))]\n",
        "mod late_tests {\n",
        "    fn b() { Command::new(\"/usr/bin/git\"); }\n",
        "}\n",
        "fn last() {}\n",
    );
    let half = production_half(source);
    for kept in ["fn first", "fn middle", "fn last"] {
        assert!(half.contains(kept), "{kept} must survive: {half:?}");
    }
    assert!(!half.contains("fn a()"));
    assert!(!half.contains("fn b()"));
    assert!(!half.contains("Command::new"));
    assert_eq!(half.matches('\n').count(), source.matches('\n').count());
}

// `any(test, ...)` and `not(test)` also hold in a production build, so a
// module carrying them is production code the scans must keep seeing.
#[test]
fn production_half_keeps_modules_whose_cfg_is_not_test_only() {
    for predicate in ["any(test, feature = \"desktop\")", "not(test)"] {
        let source = format!("#[cfg({predicate})]\nmod shipped {{\n    fn spawn() {{ Command::new(\"git\"); }}\n}}\n");
        assert!(
            production_half(&source).contains(r#"Command::new("git")"#),
            "#[cfg({predicate})] mod is production code"
        );
    }
}

/// Independent, line-based estimate of a file's production lines, written
/// without reusing `production_half`: a plain walk that enters an inline test
/// module at a test-only `#[cfg(...)]` line whose next line declares a module
/// with a body, and leaves it when a naive brace count returns to zero. Naive
/// counting is enough for an estimate compared against a 90 percent floor.
fn non_test_line_count(source: &str) -> usize {
    let mut count = 0usize;
    let mut depth: i64 = 0;
    let mut inside_test_module = false;
    let mut saw_test_cfg = false;
    for line in source.lines() {
        let trimmed = line.trim();
        if inside_test_module {
            depth += trimmed.matches('{').count() as i64;
            depth -= trimmed.matches('}').count() as i64;
            inside_test_module = depth > 0;
            continue;
        }
        if saw_test_cfg && trimmed.starts_with("mod ") && trimmed.ends_with('{') {
            inside_test_module = true;
            saw_test_cfg = false;
            depth = 1;
            continue;
        }
        if trimmed.starts_with("#[cfg(")
            && trimmed.contains("test")
            && !trimmed.contains("any(")
            && !trimmed.contains("not(test")
        {
            saw_test_cfg = true;
            continue;
        }
        saw_test_cfg = saw_test_cfg && trimmed.starts_with("#[");
        if !trimmed.is_empty() {
            count += 1;
        }
    }
    count
}

// Truncation is loud here: before F1, eight real files (env_files.rs,
// commands/oauth.rs, db/types.rs, commands/scan/tools.rs, commands/mod.rs,
// commands/reports.rs and two code_scan corpus files) lost most of their
// production lines to `production_half`.
#[test]
fn production_half_retains_the_production_lines_of_every_source_file() {
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files = Vec::new();
    rust_source_files(&src_dir, &mut files);
    assert!(!files.is_empty(), "Rust source scan found no files");

    let mut thin = Vec::new();
    for file in files {
        let relative = file
            .strip_prefix(env!("CARGO_MANIFEST_DIR"))
            .unwrap_or(&file)
            .display()
            .to_string();
        let source = std::fs::read_to_string(&file).expect("read Rust source file");
        let half = production_half(&source);
        assert_eq!(
            half.matches('\n').count(),
            source.matches('\n').count(),
            "{relative}: production_half must preserve line numbering"
        );
        let retained = half.lines().filter(|line| !line.trim().is_empty()).count();
        let expected = non_test_line_count(&source);
        if retained * 10 < expected * 9 {
            thin.push(format!("{relative} ({retained} of ~{expected})"));
        }
    }

    assert!(
        thin.is_empty(),
        "production_half must excise each inline test module and keep scanning, never truncate the file at the first one: {:?}",
        thin,
    );
}

// The fail-closed wait on the private-network rules is its own budget. While
// it shared WEBVIEW_PAGE_LOAD_WAIT, retuning page readiness silently retuned
// how long the analyzer would wait before refusing to scan at all.
#[test]
fn the_analyzer_waits_on_rules_install_with_its_own_budget() {
    let production = production_half(include_str!("webview/analyzer.rs"));
    assert!(
        production.contains("WEBVIEW_RULES_INSTALL_WAIT, ready_receiver"),
        "the private-network rules wait must use constants::WEBVIEW_RULES_INSTALL_WAIT"
    );
    assert!(
        crate::constants::WEBVIEW_RULES_INSTALL_WAIT > std::time::Duration::ZERO,
        "a zero rules-install budget would fail every scan closed"
    );
}

#[test]
fn analyzer_never_resolves_dns_on_the_navigation_thread() {
    let production = production_half(include_str!("webview/analyzer.rs"));
    assert!(
        !production.contains("_blocking("),
        "analyzer.rs must use the async validators; synchronous DNS on the webview thread stalls the UI"
    );
}

#[test]
fn elevated_commands_are_not_in_baseline_acl() {
    let default_cmds =
        command_permissions_from_default_toml(include_str!("../permissions/default.toml"));
    let manifest = command_security_manifest();
    let elevated_cmds = manifest_string_array(&manifest, "elevatedCommands");

    let leaked_to_default: Vec<_> = elevated_cmds
        .iter()
        .filter(|command| default_cmds.contains(command.as_str()))
        .collect();
    assert!(
        leaked_to_default.is_empty(),
        "Elevated commands must stay out of the baseline ACL: {:?}",
        leaked_to_default,
    );
}

#[test]
fn sensitive_capability_groups_elevated_acl_surfaces() {
    let default_capability = include_str!("../capabilities/default.json");
    assert!(
        !default_capability.contains("\"opener:default\""),
        "Do not grant the main renderer an opener default."
    );
    for permission in [
        "core:window:allow-create",
        "core:webview:allow-create-webview-window",
    ] {
        assert!(
            !default_capability.contains(permission),
            "Baseline renderer capability must not allow renderer-created windows/webviews: {}",
            permission,
        );
    }
    assert!(
        !default_capability.contains("opener:"),
        "The main renderer must not have a generic URL opener; external links cross the native-confirmed broker."
    );
    assert!(
        !default_capability.contains("store:"),
        "The main renderer must use fixed-file app settings commands, never arbitrary-path store plugin commands."
    );

    let sensitive_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("capabilities")
        .join("sensitive.json");
    assert!(
        !sensitive_path.exists(),
        "Do not reintroduce one broad sensitive.json capability; keep elevated surfaces split by feature."
    );

    let manifest = command_security_manifest();
    let elevated_permissions = manifest_string_array(&manifest, "elevatedPermissions");
    let forbidden_main_plugin_permissions =
        manifest_string_array(&manifest, "forbiddenMainWindowPluginPermissions");
    assert!(
        forbidden_main_plugin_permissions.contains("keyring:default")
            && forbidden_main_plugin_permissions.contains("updater:default"),
        "command-security.json must list renderer-forbidden plugin defaults."
    );
    for permission in &forbidden_main_plugin_permissions {
        assert!(
            !default_capability.contains(permission.as_str()),
            "Baseline renderer capability must not grant plugin permission: {}",
            permission,
        );
    }
    let elevated_capabilities = [
        (
            "sitecmd-data-admin",
            include_str!("../capabilities/data-admin.json"),
        ),
        (
            "sitecmd-external-connectors",
            include_str!("../capabilities/external-connectors.json"),
        ),
        (
            "sitecmd-filesystem-access",
            include_str!("../capabilities/filesystem-access.json"),
        ),
        (
            "sitecmd-filesystem-export",
            include_str!("../capabilities/filesystem-export.json"),
        ),
        (
            "sitecmd-project-execution",
            include_str!("../capabilities/project-execution.json"),
        ),
    ];

    for (permission, capability) in elevated_capabilities {
        assert!(
            elevated_permissions.contains(permission),
            "Feature-scoped capability must be listed in command-security.json: {}",
            permission,
        );
        assert!(
            capability.contains(permission),
            "Feature-scoped capability is missing {}",
            permission,
        );
        for other_permission in elevated_permissions
            .iter()
            .filter(|other| other.as_str() != permission)
        {
            assert!(
                !capability.contains(other_permission.as_str()),
                "Feature-scoped capability for {} must not bundle {}",
                permission,
                other_permission,
            );
        }
    }
}

#[test]
fn high_risk_commands_require_native_confirmation() {
    let mut missing_confirmations = Vec::new();
    let repo_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .and_then(Path::parent)
        .expect("repo root");
    for entry in native_confirmed_manifest_entries() {
        let path = repo_root.join(&entry.source);
        let source = std::fs::read_to_string(&path).expect("read command source");
        for step in &entry.steps {
            if !function_body_contains(&source, &step.function, &step.requires) {
                missing_confirmations.push(format!(
                    "{}::{} ({})",
                    entry.source, entry.command, step.function
                ));
            }
        }
    }

    assert!(
        missing_confirmations.is_empty(),
        "High-risk IPC commands must require native confirmation before destructive or executable work: {:?}",
        missing_confirmations,
    );
}

#[test]
fn data_admin_commands_are_native_confirmed_in_manifest() {
    let data_admin_commands =
        command_permissions_from_commands_allow(include_str!("../permissions/data_admin.toml"));
    let confirmed_commands: BTreeSet<String> = native_confirmed_manifest_entries()
        .into_iter()
        .map(|entry| entry.command)
        .collect();

    let unconfirmed_data_admin_commands: Vec<_> = data_admin_commands
        .difference(&confirmed_commands)
        .collect();
    assert!(
        unconfirmed_data_admin_commands.is_empty(),
        "Data-admin commands must be native-confirmed in command-security.json: {:?}",
        unconfirmed_data_admin_commands,
    );
}

#[test]
fn elevated_acl_commands_are_listed_in_security_manifest() {
    let manifest = command_security_manifest();
    let manifest_commands = manifest_string_array(&manifest, "elevatedCommands");
    let mut acl_commands = BTreeSet::new();
    for src in [
        include_str!("../permissions/data_admin.toml"),
        include_str!("../permissions/external_connectors.toml"),
        include_str!("../permissions/filesystem_access.toml"),
        include_str!("../permissions/filesystem_export.toml"),
        include_str!("../permissions/project_execution.toml"),
    ] {
        acl_commands.extend(command_permissions_from_commands_allow(src));
    }

    let missing_from_manifest: Vec<_> = acl_commands.difference(&manifest_commands).collect();
    let stale_in_manifest: Vec<_> = manifest_commands.difference(&acl_commands).collect();
    assert!(
        missing_from_manifest.is_empty() && stale_in_manifest.is_empty(),
        "command-security.json elevatedCommands drifted from elevated ACL.\n  missing: {:?}\n  stale: {:?}",
        missing_from_manifest,
        stale_in_manifest,
    );
}

#[test]
fn frontend_invoke_literals_match_registered_commands() {
    let repo_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("repo root");
    let src_dir = repo_root.join("src");
    let mut files = Vec::new();
    fn ts_source_files(dir: &Path, files: &mut Vec<PathBuf>) {
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                ts_source_files(&path, files);
            } else if path
                .extension()
                .is_some_and(|extension| extension == "ts" || extension == "tsx")
            {
                files.push(path);
            }
        }
    }
    ts_source_files(&src_dir, &mut files);

    let registered = app_manifest_command_names();
    let invoke_regex =
        regex::Regex::new(r#"\binvoke(?:\s*<[\s\S]*?>)?\s*\(\s*([^,\n)]+)"#).expect("invoke regex");
    let literal_regex = regex::Regex::new(r#"^["']([a-z0-9_]+)["']$"#).expect("literal regex");
    let mut missing_commands = Vec::new();
    let mut dynamic_calls = Vec::new();

    for file in files {
        let relative = file
            .strip_prefix(repo_root)
            .unwrap_or(&file)
            .to_string_lossy()
            .replace('\\', "/");
        if relative.ends_with(".test.ts")
            || relative.ends_with(".test.tsx")
            || relative.ends_with(".spec.ts")
            || relative.ends_with(".spec.tsx")
            || relative.ends_with(".behavior.ts")
            || relative.ends_with(".behavior.tsx")
            || relative.ends_with(".render.ts")
            || relative.ends_with(".render.tsx")
            || relative == "src/lib/tauri-invoke.ts"
            || relative == "src/lib/privileged-command-bridge.ts"
            || relative.starts_with("src/lib/commands/")
        {
            continue;
        }

        let source = std::fs::read_to_string(&file).expect("read frontend source");
        for capture in invoke_regex.captures_iter(&source) {
            let Some(matched) = capture.get(0) else {
                continue;
            };
            let arg = capture
                .get(1)
                .map(|value| value.as_str().trim())
                .unwrap_or("");
            let line = source[..matched.start()].lines().count() + 1;
            let Some(command) = literal_regex
                .captures(arg)
                .and_then(|literal| literal.get(1))
                .map(|value| value.as_str().to_string())
            else {
                dynamic_calls.push(format!("{}:{}", relative, line));
                continue;
            };

            if !registered.contains(&command) {
                missing_commands.push(format!("{}:{} invokes {}", relative, line, command));
            }
        }
    }

    assert!(
        dynamic_calls.is_empty(),
        "Frontend invoke calls must use literal command names so ACL drift is reviewable: {:?}",
        dynamic_calls,
    );
    assert!(
        missing_commands.is_empty(),
        "Frontend invoke calls drifted from registered Tauri commands: {:?}",
        missing_commands,
    );
}

#[test]
fn tracing_instrument_fields_do_not_record_raw_or_secretish_values() {
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files = Vec::new();
    rust_source_files(&src_dir, &mut files);

    let mut findings = Vec::new();
    for file in files {
        let source = std::fs::read_to_string(&file).expect("read Rust source file");
        for (line, attribute) in tracing_instrument_attributes(&source) {
            if tracing_field_assignment_is_unsafe(attribute) {
                let relative = file
                    .strip_prefix(env!("CARGO_MANIFEST_DIR"))
                    .unwrap_or(&file)
                    .display();
                findings.push(format!("{}:{}", relative, line));
            }
        }
    }

    assert!(
        findings.is_empty(),
        "tracing::instrument fields must not record raw or secret-like values. Use skip(...) and log parsed safe metadata instead: {:?}",
        findings,
    );
}

/// Whole words in a parameter name that mark it as a secret. Deliberately
/// tighter than `tracing_field_assignment_is_unsafe`: `environment_scope_key`,
/// `idempotency_key`, and `project_key` are identifiers, so a bare `key` is
/// only a secret in the compound forms listed in
/// `SECRET_PARAMETER_COMPOUNDS`.
const SECRET_PARAMETER_WORDS: &[&str] = &[
    "password",
    "passwd",
    "passphrase",
    "secret",
    "secrets",
    "token",
    "apikey",
    "credential",
    "credentials",
    "authorization",
    "bearer",
];

const SECRET_PARAMETER_COMPOUNDS: &[&str] =
    &["api_key", "private_key", "license_key", "signing_key"];

/// A name that ends in one of these refers to a secret without carrying it.
const IDENTIFIER_SUFFIXES: &[&str] = &["_id", "_ids", "_hash", "_fingerprint", "_kind", "_count"];

fn parameter_names_a_secret(parameter: &str) -> bool {
    let lower = parameter.to_ascii_lowercase();
    if IDENTIFIER_SUFFIXES
        .iter()
        .any(|suffix| lower.ends_with(suffix))
    {
        return false;
    }
    lower
        .split('_')
        .any(|word| SECRET_PARAMETER_WORDS.contains(&word))
        || SECRET_PARAMETER_COMPOUNDS
            .iter()
            .any(|compound| lower.contains(compound))
}

/// Parameter names listed in the attribute's `skip(...)` clause.
fn instrument_skipped_parameters(attribute: &str) -> Vec<String> {
    let Some(start) = attribute.find("skip(") else {
        return Vec::new();
    };
    let inner = &attribute[start + "skip(".len()..];
    let Some(end) = inner.find(')') else {
        return Vec::new();
    };
    inner[..end]
        .split(',')
        .map(|name| name.trim().to_string())
        .filter(|name| !name.is_empty())
        .collect()
}

/// Parameter names of the `fn` signature that follows the attribute ending at
/// byte offset `attribute_end`. Balances parentheses so closure and tuple
/// types do not end the list early, and splits only on top-level commas.
fn instrumented_fn_parameters(source: &str, attribute_end: usize) -> Vec<String> {
    let rest = &source[attribute_end..];
    let Some(fn_at) = rest.find("fn ") else {
        return Vec::new();
    };
    let after_fn = &rest[fn_at + "fn ".len()..];

    let mut angle_depth = 0i32;
    let mut list_start = None;
    let mut previous = ' ';
    for (index, ch) in after_fn.char_indices() {
        match ch {
            '<' => angle_depth += 1,
            '>' if previous != '-' => angle_depth -= 1,
            '(' if angle_depth == 0 => {
                list_start = Some(index + 1);
                break;
            }
            '{' | ';' => break,
            _ => {}
        }
        previous = ch;
    }
    let Some(list_start) = list_start else {
        return Vec::new();
    };

    let mut depth = 0i32;
    let mut list_end = None;
    for (index, ch) in after_fn[list_start..].char_indices() {
        match ch {
            '(' | '[' => depth += 1,
            ')' | ']' if depth > 0 => depth -= 1,
            ')' => {
                list_end = Some(list_start + index);
                break;
            }
            _ => {}
        }
    }
    let Some(list_end) = list_end else {
        return Vec::new();
    };

    let list = &after_fn[list_start..list_end];
    let mut parameters = Vec::new();
    let mut depth = 0i32;
    let mut current = String::new();
    let mut previous = ' ';
    for ch in list.chars() {
        match ch {
            '(' | '[' | '<' => depth += 1,
            ')' | ']' => depth -= 1,
            '>' if previous != '-' => depth -= 1,
            ',' if depth == 0 => {
                parameters.push(std::mem::take(&mut current));
                previous = ch;
                continue;
            }
            _ => {}
        }
        current.push(ch);
        previous = ch;
    }
    parameters.push(current);

    parameters
        .iter()
        .filter_map(|parameter| {
            let pattern = parameter.split(':').next().unwrap_or("").trim();
            let name = pattern.trim_start_matches("mut ").trim();
            if name.is_empty()
                || name
                    .trim_start_matches('&')
                    .trim_start_matches("mut ")
                    .trim()
                    == "self"
            {
                None
            } else {
                Some(name.to_string())
            }
        })
        .collect()
}

#[test]
fn secret_parameter_guardrail_reads_signatures() {
    let source = concat!(
        "#[",
        "tracing::instrument(skip(url), fields(strategy = %strategy))]\n",
        "pub async fn fetch_report<F: Fn(&str) -> bool>(\n",
        "    url: &str,\n",
        "    strategy: &str,\n",
        "    api_key: Option<&str>,\n",
        "    on_retry: F,\n",
        ") -> Result<(), String> {\n",
        "    Ok(())\n",
        "}\n",
    );
    let (_, attribute) = tracing_instrument_attributes(source)[0];
    let end = attribute.as_ptr() as usize - source.as_ptr() as usize + attribute.len();
    assert_eq!(
        instrumented_fn_parameters(source, end),
        ["url", "strategy", "api_key", "on_retry"]
    );
    assert_eq!(instrument_skipped_parameters(attribute), ["url"]);
    assert_eq!(
        instrument_skipped_parameters(concat!(
            "#[",
            "tracing::instrument(skip(app, db, installation_token))]"
        )),
        ["app", "db", "installation_token"]
    );
    assert!(instrument_skipped_parameters(concat!("#[", "tracing::instrument]")).is_empty());

    let method = concat!(
        "#[",
        "tracing::instrument(skip(self))]\nfn run(&mut self, mut token: String) {}\n"
    );
    let (_, attribute) = tracing_instrument_attributes(method)[0];
    let end = attribute.as_ptr() as usize - method.as_ptr() as usize + attribute.len();
    assert_eq!(instrumented_fn_parameters(method, end), ["token"]);

    for secret in [
        "api_key",
        "installation_token",
        "passphrase",
        "client_secret",
        "license_key",
    ] {
        assert!(
            parameter_names_a_secret(secret),
            "{secret} must count as a secret"
        );
    }
    for identifier in [
        "environment_scope_key",
        "idempotency_key",
        "project_key",
        "max_tokens",
        "token_id",
        "token_hash",
        "url",
    ] {
        assert!(
            !parameter_names_a_secret(identifier),
            "{identifier} is not a secret"
        );
    }
}

/// `tracing::instrument` records every parameter it does not skip as a span
/// field. tracing's `log` bridge forwards span creation to the log sink, so a
/// secret parameter left off `skip(...)` is one log-level change away from a
/// rotating log file. Companion to
/// `tracing_instrument_fields_do_not_record_raw_or_secretish_values`, which
/// covers explicit `fields(...)` but not implicit parameter capture.
#[test]
fn tracing_instrument_skips_secret_shaped_parameters() {
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files = Vec::new();
    rust_source_files(&src_dir, &mut files);

    let mut findings = Vec::new();
    for file in files {
        let source = std::fs::read_to_string(&file).expect("read Rust source file");
        for (line, attribute) in tracing_instrument_attributes(&source) {
            if attribute.contains("skip_all") {
                continue;
            }
            let skipped = instrument_skipped_parameters(attribute);
            let end = attribute.as_ptr() as usize - source.as_ptr() as usize + attribute.len();
            for parameter in instrumented_fn_parameters(&source, end) {
                if parameter_names_a_secret(&parameter) && !skipped.contains(&parameter) {
                    let relative = file
                        .strip_prefix(env!("CARGO_MANIFEST_DIR"))
                        .unwrap_or(&file)
                        .display();
                    findings.push(format!("{}:{} records `{}`", relative, line, parameter));
                }
            }
        }
    }

    assert!(
        findings.is_empty(),
        "tracing::instrument must skip secret-shaped parameters (add them to skip(...)): {:?}",
        findings,
    );
}

/// Empty by design: every response body is read through the limited readers.
/// Adding an entry here is a regression, not a migration step.
const UNCAPPED_BODY_READ_FILES: &[&str] = &[];

#[test]
fn response_bodies_are_read_only_through_the_limited_readers() {
    let uncapped = regex::Regex::new(r"\.(?:json|text)(?:::<[^>]*>)?\(\)\s*\.await")
        .expect("uncapped read pattern");
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files = Vec::new();
    rust_source_files(&src_dir, &mut files);

    let mut unexpected = Vec::new();
    let mut listed_but_clean: Vec<&str> = UNCAPPED_BODY_READ_FILES.to_vec();
    for file in files {
        let relative = file
            .strip_prefix(env!("CARGO_MANIFEST_DIR"))
            .unwrap_or(&file)
            .display()
            .to_string();
        if relative == "src/http_client.rs" || relative.ends_with("_tests.rs") {
            continue;
        }
        let source = std::fs::read_to_string(&file).expect("read Rust source file");
        let hits = uncapped.find_iter(&production_half(&source)).count();
        if hits == 0 {
            continue;
        }
        if UNCAPPED_BODY_READ_FILES.contains(&relative.as_str()) {
            listed_but_clean.retain(|listed| *listed != relative);
        } else {
            unexpected.push(format!("{relative} ({hits})"));
        }
    }

    assert!(
        unexpected.is_empty(),
        "Read response bodies through http_client::read_json_limited or read_text_limited with a cap from constants.rs. This scan covers src/ only, excluding src/http_client.rs and files named *_tests.rs; crates/cli and crates/engine are not scanned: {:?}",
        unexpected,
    );
    assert!(
        listed_but_clean.is_empty(),
        "These files no longer contain uncapped reads; remove them from UNCAPPED_BODY_READ_FILES so the ratchet only moves toward zero: {:?}",
        listed_but_clean,
    );
}

// The scan roots and the failure messages must not drift apart: a message
// that claims wider coverage than the walk sends a reader hunting a violation
// the scan never looks for. This pins what the messages now state.
#[test]
fn the_source_scans_cover_only_the_roots_their_messages_name() {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let src_dir = manifest.join("src");
    let commands_dir = src_dir.join("commands");
    let crates_dir = manifest.join("crates");

    let mut src_files = Vec::new();
    rust_source_files(&src_dir, &mut src_files);
    let mut command_files = Vec::new();
    rust_source_files(&commands_dir, &mut command_files);
    let mut crate_files = Vec::new();
    rust_source_files(&crates_dir, &mut crate_files);

    assert!(!src_files.is_empty(), "src/ scan found no files");
    assert!(
        !command_files.is_empty(),
        "src/commands/ scan found no files"
    );
    assert!(
        !crate_files.is_empty(),
        "crates/ holds Rust sources the src/ scans never walk, which is exactly what their messages must keep saying"
    );
    assert!(
        src_files.iter().all(|file| !file.starts_with(&crates_dir)),
        "the git-spawn and uncapped-read scans walk src/ only, never crates/cli or crates/engine"
    );
    assert!(
        command_files.len() < src_files.len()
            && command_files.iter().all(|file| file.starts_with(&src_dir)),
        "the inline-git scan walks src/commands/ only, a strict subset of src/"
    );
}

// Negative control: the pattern sees the turbofish and the multi-line form.
#[test]
fn uncapped_read_guard_detects_every_spelling() {
    let uncapped = regex::Regex::new(r"\.(?:json|text)(?:::<[^>]*>)?\(\)\s*\.await")
        .expect("uncapped read pattern");
    assert!(uncapped.is_match("resp.json().await"));
    assert!(uncapped.is_match("resp.json::<OsvVuln>().await"));
    assert!(uncapped.is_match("resp\n        .text()\n        .await"));
    assert!(!uncapped.is_match(".json(&body).send().await"));
}

/// Line numbers of sync `core::git` helper calls that sit inside an `async fn`
/// without a `run_blocking`/`spawn_blocking` wrapper lexically enclosing the
/// call. A wrapper only covers a call while the call site is still nested
/// inside that wrapper's own argument list or closure body: brace/paren depth
/// is tracked from each `fn` signature forward, a `run_blocking(` or
/// `spawn_blocking(` token records the depth it was seen at, and that record
/// is dropped as soon as depth returns to (or below) that level. A wrapper
/// that already closed earlier in the same function therefore cannot cover a
/// later, unrelated call.
fn inline_sync_git_calls(source: &str) -> Vec<usize> {
    let call = regex::Regex::new(
        r"\bgit::(?:get_git_status|get_commits_since|get_commits_between|get_recent_commits|checkout_head_and_clean)\(",
    )
    .expect("git call pattern");
    let signature = regex::Regex::new(r"^\s*(?:pub(?:\([a-z]+\))?\s+)?(async\s+)?fn\s+\w+")
        .expect("fn signature pattern");
    let wrapper = regex::Regex::new(r"\b(?:run_blocking|spawn_blocking)\(").expect("wrapper");

    let mut findings = Vec::new();
    let mut is_async = false;
    let mut depth: i64 = 0;
    let mut open_wrappers: Vec<i64> = Vec::new();

    let production = production_half(source);
    for (index, line) in production.lines().enumerate() {
        if let Some(captures) = signature.captures(line) {
            is_async = captures.get(1).is_some();
        }

        let wrapper_starts: Vec<usize> = wrapper.find_iter(line).map(|m| m.start()).collect();
        let call_starts: Vec<usize> = call.find_iter(line).map(|m| m.start()).collect();

        for (byte, ch) in line.char_indices() {
            if wrapper_starts.contains(&byte) {
                open_wrappers.push(depth);
            }
            if call_starts.contains(&byte) && is_async && open_wrappers.is_empty() {
                findings.push(index + 1);
            }
            match ch {
                '{' | '(' => depth += 1,
                '}' | ')' => {
                    depth -= 1;
                    while open_wrappers.last().is_some_and(|&start| depth <= start) {
                        open_wrappers.pop();
                    }
                }
                _ => {}
            }
        }
    }
    findings
}

#[test]
fn sync_git_helpers_are_not_called_inline_from_async_commands() {
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("src")
        .join("commands");
    let mut files = Vec::new();
    rust_source_files(&src_dir, &mut files);
    let mut findings = Vec::new();
    for file in files {
        let relative = file
            .strip_prefix(env!("CARGO_MANIFEST_DIR"))
            .unwrap_or(&file)
            .display()
            .to_string();
        if relative.ends_with("_tests.rs") {
            continue;
        }
        let source = std::fs::read_to_string(&file).expect("read Rust source file");
        for line in inline_sync_git_calls(&source) {
            findings.push(format!("{relative}:{line}"));
        }
    }
    assert!(
        findings.is_empty(),
        "sync git helpers block on a child process; call git::get_git_status_async or git::get_commits_since_async, or run the helper inside run_blocking. This scan covers src/commands/ only, excluding files named *_tests.rs: {:?}",
        findings,
    );
}

#[test]
fn inline_git_call_scan_sees_async_bodies_and_ignores_wrapped_or_sync_ones() {
    let inline = "pub async fn a() -> Result<(), String> {\n    let s = git::get_git_status(&p, 1);\n    Ok(())\n}\n";
    assert_eq!(inline_sync_git_calls(inline), vec![2]);

    let wrapped = "pub async fn b() {\n    run_blocking(move || {\n        git::get_recent_commits(&p, 100)\n    }).await\n}\n";
    assert!(inline_sync_git_calls(wrapped).is_empty());

    let sync = "fn c() {\n    git::get_commits_since(&p, since)\n}\n";
    assert!(inline_sync_git_calls(sync).is_empty());

    let async_wrapper = "pub async fn d() {\n    git::get_git_status_async(p, 1).await\n}\n";
    assert!(inline_sync_git_calls(async_wrapper).is_empty());
}

// A wrapper that has already closed earlier in the function must not shield a
// later, unrelated call: this is the blind spot the depth tracking closes.
#[test]
fn inline_git_call_scan_does_not_let_a_closed_wrapper_cover_a_later_call() {
    let closed_then_bare = "pub async fn e() -> Result<(), String> {\n    run_blocking(move || db.get_project_path(id)).await?;\n    let s = git::get_git_status(&path, 20);\n    Ok(())\n}\n";
    assert_eq!(inline_sync_git_calls(closed_then_bare), vec![3]);

    let genuinely_wrapped = "pub async fn f() -> Result<(), String> {\n    run_blocking(move || db.get_project_path(id)).await?;\n    let status = run_blocking(move || {\n        git::get_git_status(&path, 20)\n    })\n    .await?;\n    Ok(())\n}\n";
    assert!(inline_sync_git_calls(genuinely_wrapped).is_empty());
}

/// Number of Tauri commands whose signature still returns `Result<_, String>`.
/// Lower it with every migration commit; it must never rise. Measure with the
/// assertion message below.
const STRING_RESULT_COMMAND_BUDGET: usize = 100;

fn string_result_command_count(source: &str) -> usize {
    let signature = regex::Regex::new(
        r#"#\[(?:cfg_attr\(feature = "desktop", )?tauri::command\)?\][^{]*?fn\s+\w+[^{]*?->\s*Result<[^{]*?,\s*String>"#,
    )
    .expect("command signature pattern");
    signature.find_iter(&production_half(source)).count()
}

#[test]
fn string_returning_commands_only_decrease() {
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files = Vec::new();
    rust_source_files(&src_dir, &mut files);
    let total: usize = files
        .iter()
        .filter(|file| !file.to_string_lossy().ends_with("_tests.rs"))
        .map(|file| string_result_command_count(&std::fs::read_to_string(file).expect("read")))
        .sum();
    assert_eq!(
        total, STRING_RESULT_COMMAND_BUDGET,
        "commands returning Result<_, String> changed; set STRING_RESULT_COMMAND_BUDGET to {total} only if it went down, and migrate the command to CommandError otherwise"
    );
}

#[test]
fn string_result_command_scan_sees_both_attribute_forms() {
    let bare = format!(
        "#[{}]\npub async fn a(x: i64) -> Result<(), String> {{}}\n",
        concat!("tauri", "::command")
    );
    assert_eq!(string_result_command_count(&bare), 1);
    let cfg_attr = format!(
        "#[cfg_attr(feature = \"desktop\", {})]\npub async fn b() -> Result<Vec<u8>, String> {{}}\n",
        concat!("tauri", "::command")
    );
    assert_eq!(string_result_command_count(&cfg_attr), 1);
    let migrated = format!(
        "#[{}]\npub async fn c() -> Result<(), CommandError> {{}}\n",
        concat!("tauri", "::command")
    );
    assert_eq!(string_result_command_count(&migrated), 0);
}

/// `run_blocking(` call sites in src/. Lower with every migration commit.
const RUN_BLOCKING_CALL_BUDGET: usize = 164;
/// Sync `self.execute(`/`self.execute_mut(`/`self.execute_with_timeout(` calls
/// in src/db/. Lower as domain methods move to `run`/`run_mut`.
const SYNC_DB_EXECUTE_BUDGET: usize = 205;

fn count_matches(dir: &Path, pattern: &regex::Regex) -> usize {
    let mut files = Vec::new();
    rust_source_files(dir, &mut files);
    files
        .iter()
        .filter(|file| !file.to_string_lossy().ends_with("_tests.rs"))
        .map(|file| {
            let source = std::fs::read_to_string(file).expect("read Rust source file");
            pattern.find_iter(&production_half(&source)).count()
        })
        .sum()
}

#[test]
fn blocking_database_call_sites_only_decrease() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let run_blocking = count_matches(
        &root,
        &regex::Regex::new(r"\brun_blocking\(").expect("run_blocking pattern"),
    );
    assert_eq!(
        run_blocking, RUN_BLOCKING_CALL_BUDGET,
        "run_blocking call sites changed; set RUN_BLOCKING_CALL_BUDGET to {run_blocking} only if it went down"
    );
    let sync_execute = count_matches(
        &root.join("db"),
        &regex::Regex::new(r"self\.execute(?:_mut)?(?:_with_timeout)?\(").expect("execute pattern"),
    );
    assert_eq!(
        sync_execute, SYNC_DB_EXECUTE_BUDGET,
        "sync Database::execute call sites changed; set SYNC_DB_EXECUTE_BUDGET to {sync_execute} only if it went down"
    );
}

/// Calls to the three legacy local-origin predicates outside their definitions.
/// Lower as callers move to `LocalOrigin::classify`; delete the predicates at 0.
/// `scan_origin_allows_local_dev` is gone: `LocalOrigin` carries the reach now.
const LEGACY_LOCAL_PREDICATE_BUDGET: usize = 15;

#[test]
fn legacy_local_origin_predicates_only_decrease() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let pattern =
        regex::Regex::new(r"\b(?:is_strict_localhost|is_localhost|is_local_dev_domain)\(")
            .expect("predicate pattern");
    let definitions =
        regex::Regex::new(r"fn (?:is_strict_localhost|is_localhost|is_local_dev_domain)\(")
            .expect("definition pattern");
    let mut files = Vec::new();
    rust_source_files(&root, &mut files);
    let total: usize = files
        .iter()
        .filter(|file| !file.to_string_lossy().ends_with("_tests.rs"))
        .map(|file| {
            let source = std::fs::read_to_string(file).expect("read");
            let production = production_half(&source);
            pattern.find_iter(&production).count() - definitions.find_iter(&production).count()
        })
        .sum();
    assert_eq!(
        total, LEGACY_LOCAL_PREDICATE_BUDGET,
        "legacy local-origin predicate calls changed; set LEGACY_LOCAL_PREDICATE_BUDGET to {total} only if it went down"
    );
}

#[test]
fn one_crypto_provider_and_one_root_store_remain() {
    // webpki-roots is deliberately excluded here: it still reaches Cargo.lock
    // through the accepted, off-by-default `browser` feature's build chain
    // (headless_chrome -> auto_generate_cdp -> ureq), the same exception
    // deny.toml already documents. This test only guards the crypto
    // provider and the code we control (below).
    let lock = include_str!("../Cargo.lock");
    for crate_name in ["aws-lc-rs", "aws-lc-sys"] {
        assert!(
            !lock.contains(&format!("name = \"{crate_name}\"")),
            "{crate_name} is back in Cargo.lock; reqwest must use rustls-no-provider and every rustls ClientConfig must use the platform verifier on ring"
        );
    }
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files = Vec::new();
    rust_source_files(&src_dir, &mut files);
    // Excludes `_tests.rs` files (this file included) so the assertion's own
    // string literal below cannot match itself.
    for file in files
        .iter()
        .filter(|file| !file.to_string_lossy().ends_with("_tests.rs"))
    {
        let source = std::fs::read_to_string(file).expect("read");
        assert!(
            !source.contains("webpki_roots::"),
            "{} still uses webpki-roots",
            file.display()
        );
    }
}

/// Total `#[tracing::instrument]` attributes in src/. Lower as trivial getters
/// and hot paths lose theirs; it must never rise without a reviewed reason.
const TRACING_INSTRUMENT_BUDGET: usize = 609;

#[test]
fn tracing_instrument_count_only_decreases() {
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files = Vec::new();
    rust_source_files(&src_dir, &mut files);
    let total: usize = files
        .iter()
        .map(|file| {
            tracing_instrument_attributes(&std::fs::read_to_string(file).expect("read")).len()
        })
        .sum();
    assert_eq!(
        total, TRACING_INSTRUMENT_BUDGET,
        "tracing::instrument count changed; set TRACING_INSTRUMENT_BUDGET to {total} only if it went down"
    );
}

#[test]
fn broker_threat_model_names_every_scope_and_its_sensitive_commands() {
    let doc = include_str!("../../../../docs/engineering/privileged-broker-threat-model.md");
    for scope in crate::commands::privileged_command_broker_scopes() {
        assert!(
            doc.contains(scope.broker_command),
            "threat model must name {}",
            scope.broker_command
        );
        for command in scope.sensitive {
            assert!(
                doc.contains(command),
                "threat model must list the sensitive command {command}"
            );
        }
    }
    assert!(
        doc.contains("compromised renderer"),
        "the document must state the boundary the broker does not defend"
    );
}

/// The reverse direction of the test above: every command the threat model's
/// scope table calls sensitive must actually be gated in code. Without this,
/// a command documented as needing native intent (update_project_path was
/// one) can silently ship with no dialog.
#[test]
fn broker_scope_table_sensitive_commands_are_gated_in_code() {
    let doc = include_str!("../../../../docs/engineering/privileged-broker-threat-model.md");
    for scope in crate::commands::privileged_command_broker_scopes() {
        let row = doc
            .lines()
            .find(|line| {
                line.starts_with('|') && line.contains(&format!("`{}`", scope.broker_command))
            })
            .unwrap_or_else(|| panic!("scope table row missing for {}", scope.broker_command));
        let cells: Vec<&str> = row.split('|').map(str::trim).collect();
        let sensitive_cell = cells
            .get(3)
            .unwrap_or_else(|| panic!("sensitive column missing for {}", scope.broker_command));
        let documented: Vec<&str> = sensitive_cell.split('`').skip(1).step_by(2).collect();
        for command in documented {
            assert!(
                scope.sensitive.contains(&command),
                "threat model lists {command} as sensitive for {} but code does not gate it",
                scope.broker_command
            );
        }
        if scope.sensitive.is_empty() {
            assert_eq!(
                *sensitive_cell, "none",
                "{} has no sensitive commands in code; the doc must say none",
                scope.broker_command
            );
        }
    }
}
