//! Registers custom Tauri commands with the v2 ACL manifest.
//! New commands must appear in both `APP_COMMANDS` and `lib.rs`'s
//! `invoke_handler!`; a parity test enforces the contract.

mod build_config;

#[cfg(feature = "desktop")]
const APP_COMMANDS: &[&str] = &[
    "ping",
    "get_app_setting",
    "set_app_setting",
    "add_project",
    "add_project_by_url",
    "rename_project",
    "get_projects",
    "get_all_projects_summary",
    "get_all_projects_work_summary",
    "get_project_signal_snapshot",
    "get_project_nav_badge_snapshot",
    "get_dashboard_snapshot",
    "get_dashboard_reference_signals",
    "invalidate_project_signal_snapshot",
    "dismiss_first_scan_banner",
    "get_connected_status",
    "inspect_connected_sync",
    "issue_data_admin_command_token",
    "issue_external_connector_command_token",
    "issue_filesystem_access_command_token",
    "issue_filesystem_export_command_token",
    "issue_project_execution_command_token",
    "issue_sensitive_privileged_command_token",
    "run_data_admin_command",
    "run_filesystem_export_command",
    "run_external_connector_command",
    "run_filesystem_access_command",
    "run_project_execution_command",
    "add_environment_url",
    "get_integrations",
    "get_telemetry_consent",
    "set_telemetry_consent",
    "send_telemetry_request",
    "get_telemetry_delete_proof_hash",
    "clear_telemetry_delete_secret",
    "get_db_size",
    "run_webview_analysis",
    "verify_scan_checks",
    "get_scan_executions",
    "get_scan_execution_detail",
    "get_score_trend",
    "get_resolved_issues",
    "build_prompt",
    "export_scan_markdown",
    "discover_sitemap",
    "fetch_sitemap_manual",
    "save_site_pages",
    "get_site_pages",
    "get_scan_scope",
    "get_scan_scope_revision",
    "set_scan_scope",
    "refresh_sitemap",
    "set_site_sitemap_url",
    "get_or_create_site_id",
    "cancel_scan",
    "check_ssl",
    "get_events",
    "record_verification_event",
    "record_update_event",
    "record_search_event",
    "record_security_event",
    "get_correlations",
    "refresh_events",
    "backfill_events",
    "generate_report_data",
    "generate_report_html",
    "render_report_html_from_data",
    "save_report_history",
    "get_report_history",
    "save_scan_schedule",
    "get_scan_schedule",
    "get_fix_document",
    "restart_app",
    "log_frontend",
    "update_tray_scan_status",
    "update_tray_summary",
    "send_actionable_desktop_notification",
    "get_webhook_configs",
    "get_issue_links",
    "get_issue_link_for_check",
    "block_issue",
    "count_unread_alerts",
    "dismiss_alert",
    "get_alerts",
    "get_current_score",
    "get_score_snapshot_history",
    "get_issue_state",
    "get_issue_check_memory",
    "get_work_items",
    "ignore_issue",
    "mark_alerts_viewed_bulk",
    "mark_alert_unread",
    "mark_alert_viewed",
    "mark_issue_fixed",
    "reopen_issue",
    "snooze_issue",
    "verify_issue",
    "create_fix_attempt",
    "get_fix_attempt_for_issue",
    "cancel_fix_attempt",
    "detect_agent_tools",
    "get_agent_tool_manual_config",
    "get_license_status",
    "get_pages_with_issues",
    "get_issues_for_page",
    "dismiss_integration_hint",
    "preview_deploy_risk_cmd",
    "whatif_resolve_cmd",
    "get_catalog_status",
    "confirm_link_license_activation",
    "retry_catalog_refresh",
    "resolve_fix_guide",
];

fn main() {
    let source_root = std::path::PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").unwrap());
    build_config::configure_runtime(&source_root);

    #[cfg(feature = "desktop")]
    {
        let attributes = tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS));
        tauri_build::try_build(attributes).expect("failed to run tauri-build");
    }
}
