//! Test-only generation of MCP license-validation timing constants.

#[cfg(test)]
mod tests {
    use serde::Serialize;

    use crate::licensing::config::{
        FINAL_GRACE_PERIOD_SECS, OFFLINE_GRACE_PERIOD_SECS, VALIDATION_INTERVAL_SECS,
    };

    const GENERATED_NOTICE: &str = "GENERATED by licensing manifest test in \
        apps/desktop/src-tauri/src/licensing/. Do not edit by hand: change \
        licensing/config.rs, run cargo test, commit the diff.";

    /// Struct field order pins the JSON key order.
    #[derive(Serialize)]
    struct LicensingManifest {
        #[serde(rename = "_generated")]
        generated: &'static str,
        validation_interval_secs: u64,
        offline_grace_period_secs: u64,
        final_grace_period_secs: u64,
    }

    fn licensing_manifest_json() -> String {
        let manifest = LicensingManifest {
            generated: GENERATED_NOTICE,
            validation_interval_secs: VALIDATION_INTERVAL_SECS,
            offline_grace_period_secs: OFFLINE_GRACE_PERIOD_SECS,
            final_grace_period_secs: FINAL_GRACE_PERIOD_SECS,
        };

        serde_json::to_string_pretty(&manifest).expect("serialize licensing manifest") + "\n"
    }

    #[test]
    fn manifest_carries_no_feature_table_or_limits() {
        let json: serde_json::Value =
            serde_json::from_str(&licensing_manifest_json()).expect("manifest parses");
        let object = json.as_object().expect("manifest object");

        for retired in [
            "features",
            "free_daily_scan_limit",
            "free_monthly_fix_limit",
            "free_history_limit",
            "core_site_limit",
            "tier_order",
        ] {
            assert!(
                !object.contains_key(retired),
                "manifest must not carry retired key {retired}"
            );
        }
        assert_eq!(json["validation_interval_secs"], 86400);
    }

    // Regenerates a stale MCP manifest, then fails so the diff is committed.
    #[test]
    fn license_constants_json_is_in_sync_with_consumers() {
        let expected = licensing_manifest_json();

        let manifest_dir = std::path::PathBuf::from(env!("SITECMD_SOURCE_ROOT"));
        let desktop_root = manifest_dir.parent().expect("desktop app root");
        let apps_root = desktop_root.parent().expect("apps root");
        let target = apps_root
            .join("mcp-server")
            .join("src")
            .join("license_constants.json");

        let actual = std::fs::read_to_string(&target).unwrap_or_default();
        if actual != expected {
            let parent = target.parent().expect("manifest target dir");
            std::fs::create_dir_all(parent).expect("create generated dir");
            std::fs::write(&target, &expected).expect("write license_constants.json");
            panic!(
                "stale license_constants.json regenerated at {}; \
                 re-run cargo test and commit the diff",
                target.display()
            );
        }

        let frontend_copy = desktop_root
            .join("src")
            .join("generated")
            .join("license_constants.json");
        assert!(
            !frontend_copy.exists(),
            "retired frontend manifest copy must stay deleted: {}",
            frontend_copy.display()
        );
    }
}
